#!/bin/sh

REPOSITORY=centreon-connectors
VERSION=1.1.1

ORIGIN_URL=https://github.com/centreon-deb/$REPOSITORY
ORIGIN_REMOTE=origin
UPSTREAM_URL=https://github.com/centreon/$REPOSITORY
UPSTREAM_REMOTE=upstream


git clone $ORIGIN_URL
cd $REPOSITORY
git remote add $UPSTREAM_REMOTE $UPSTREAM_URL
git fetch $UPSTREAM_REMOTE

git fetch -a --tags
git merge $UPSTREAM_REMOTE/master

cat <<EOF
To get build instructions:
  git show remotes/$ORIGIN_REMOTE/debian:README.Build.md

To build:
   cd $REPOSITORY && git deb-pkg -C -U -u $VERSION -d $ORIGIN_REMOTE/debian build
EOF
